//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSClientApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class APIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPSClientApp.Resources.APIResource", typeof(APIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Documentation.
        /// </summary>
        public static string APIDoc {
            get {
                return ResourceManager.GetString("APIDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Parameters.
        /// </summary>
        public static string BodyParams {
            get {
                return ResourceManager.GetString("BodyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DeleteMethod {
            get {
                return ResourceManager.GetString("DeleteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Output.
        /// </summary>
        public static string ExampleOutput {
            get {
                return ResourceManager.GetString("ExampleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Request.
        /// </summary>
        public static string ExampleRequest {
            get {
                return ResourceManager.GetString("ExampleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Method.
        /// </summary>
        public static string HttpMethod {
            get {
                return ResourceManager.GetString("HttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Data.
        /// </summary>
        public static string PostData {
            get {
                return ResourceManager.GetString("PostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string PostMethod {
            get {
                return ResourceManager.GetString("PostMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Parameters.
        /// </summary>
        public static string QueryParams {
            get {
                return ResourceManager.GetString("QueryParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Information.
        /// </summary>
        public static string ResourceInfo {
            get {
                return ResourceManager.GetString("ResourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource URL.
        /// </summary>
        public static string ResourceURL {
            get {
                return ResourceManager.GetString("ResourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Format.
        /// </summary>
        public static string ResponseFormat {
            get {
                return ResourceManager.GetString("ResponseFormat", resourceCulture);
            }
        }
    }
}
